### PR TITLE
FAPEC_FITS new parameters added

### PR DESCRIPTION
**Pull request by OscarMaireles**

### CODE REVIEW

**Review by miguelinux314 — CHANGES_REQUESTED** [review]
Thanks! The following needs to be addressed:
- the dtype , be and signed flags should be selected based on the image geometry
- line 271 seems to be duped in 272
- please delete the name function, the AbstractCodec class already provides this functionality by default (including all parameters)
- we may want to test the -chunk and -bl parameters at some point. Please add those parameters to param_dict
- All parameters (in particular the od, dwt, chunk and bl should be part of the __init__ signature so that we can instantiate it with the desired parameters.

**Comment by OscarMaireles** [comment]
FAPEC comments have been addressed. Plus, an update on zstandard codec to add dictionary training has been made.

**Comment by miguelinux314** [comment]
Thank you! Still a couple of things to be addressed:
- The idea is for to inherit from FAPEC_Abstract and call the initializer appropriately. Please take a look at the other classes and update FAPEC_FITS accordingly. Note that the current code does not even pass the created param_dict to the WrapperInitializer - please make sure to test the codec before the next pull request.
- For Zstandard, the idea would be to have 2 different classes: the first one that applies it normally (the class that already existed) and another one that generates a specific dictionary. However, the current PR simply overwrites the previously existing behavior. 
- For the second Zstandard class, we need to consider the size of the side information (and right now it is not). To do this, you can overwrite the compress(*) and decompress(*) methods, i.e., so that they use the tarlite module we discussed this morning. If needed, you can check out the JPEG-LS and M-CALIC codec sources for examples on how to employ this tarlite module. Please verify manually that the reported compressed size is as expected, i.e., only a few bytes larger than the sum of sizes of the compressed file and the side information file.

**Comment by OscarMaireles** [comment]
Comments have been addressed

**Comment by OscarMaireles** [comment]
zstd-dev.zip changed to zstd-1.1.3.zip

**Comment by miguelinux314** [comment]
Merged and cleaned up in 4b50c1e

**Pull request closed without merging**
